import { createCommandsProvider } from '@yaos-git/toolkit/tui/commands';
import type { MeshSyncCommand, MeshSyncDeps } from './types.js';

const notInputting = (deps: MeshSyncDeps) =>
	deps.ui.activeOverlay === 'none' && !deps.ui.inputActive;

const inBrowse = (deps: MeshSyncDeps) =>
	notInputting(deps) && deps.ui.viewMode === 'browse';

const inDetail = (deps: MeshSyncDeps) =>
	notInputting(deps) && deps.ui.viewMode === 'detail';

const PROJECT_COMMANDS: MeshSyncCommand[] = [
	{
		id: 'QUIT',
		keys: [{ textKey: 'q' }],
		displayKey: 'q',
		displayText: 'quit',
		helpSection: 'General',
		footer: 'priority',
		footerOrder: 99,
		isEnabled: (deps) => inBrowse(deps),
		execute: (deps) => deps.onQuit(),
		needsConfirmation: (deps) => deps.isWatching,
		confirmMessage: 'Watcher active. Quit?',
	},
	{
		id: 'HELP',
		keys: [{ textKey: 'h' }],
		displayKey: 'h',
		displayText: 'help',
		helpSection: 'General',
		footer: 'priority',
		footerOrder: 98,
		isEnabled: notInputting,
		execute: (deps) => deps.ui.setActiveOverlay('help'),
	},

	// ── Browse mode ───────────────────────────────────────────────────
	{
		id: 'NAV_UP',
		keys: [{ specialKey: 'up' }],
		displayKey: '\u2191 / \u2193',
		displayText: 'move',
		helpSection: 'Navigation',
		footer: 'priority',
		footerOrder: 1,
		isEnabled: inBrowse,
		execute: () => {},
	},
	{
		id: 'NAV_DOWN',
		keys: [{ specialKey: 'down' }],
		displayKey: '\u2193',
		displayText: 'down',
		helpSection: 'Navigation',
		footer: 'hidden',
		isEnabled: inBrowse,
		execute: () => {},
	},
	{
		id: 'OPEN',
		keys: [{ specialKey: 'return' }],
		displayKey: 'Enter',
		displayText: 'open',
		helpSection: 'Navigation',
		helpLabel: 'Open entry detail view',
		footer: 'priority',
		footerOrder: 2,
		isEnabled: inBrowse,
		execute: () => {},
	},
	{
		id: 'SYNC_ONE',
		keys: [{ textKey: 's' }],
		displayKey: 's',
		displayText: 'sync',
		helpSection: 'Actions',
		helpLabel: 'Sync selected entry now',
		footer: 'priority',
		footerOrder: 3,
		isEnabled: inBrowse,
		execute: () => {},
	},
	{
		id: 'SYNC_ALL',
		keys: [{ textKey: 'S', shift: true }],
		displayKey: 'S',
		displayText: 'sync all',
		helpSection: 'Actions',
		footer: 'optional',
		isEnabled: inBrowse,
		execute: () => {},
	},
	{
		id: 'WATCH',
		keys: [{ textKey: 'w' }],
		displayKey: 'w',
		displayText: 'watch',
		helpSection: 'Actions',
		footer: 'optional',
		isEnabled: inBrowse,
		execute: () => {},
	},
	{
		id: 'NEW_ENTRY',
		keys: [{ textKey: 'n' }],
		displayKey: 'n',
		displayText: 'new',
		helpSection: 'Actions',
		footer: 'optional',
		isEnabled: inBrowse,
		execute: () => {},
	},
	{
		id: 'DELETE_ENTRY',
		keys: [{ textKey: 'd' }],
		displayKey: 'd',
		displayText: 'delete',
		helpSection: 'Actions',
		footer: 'optional',
		isEnabled: inBrowse,
		execute: () => {},
	},

	// ── Detail mode ───────────────────────────────────────────────────
	{
		id: 'BACK',
		keys: [{ specialKey: 'escape' }],
		displayKey: 'Esc',
		displayText: 'back',
		helpSection: 'Navigation',
		footer: 'priority',
		footerOrder: 99,
		isEnabled: inDetail,
		execute: () => {},
	},
	{
		id: 'COL_NAV',
		keys: [{ leftArrow: true }],
		displayKey: '\u2190 / \u2192',
		displayText: 'columns',
		helpSection: 'Navigation',
		footer: 'priority',
		footerOrder: 1,
		isEnabled: inDetail,
		execute: () => {},
	},
	{
		id: 'CHAIN_NAV',
		keys: [{ specialKey: 'up' }],
		displayKey: '\u2191 / \u2193',
		displayText: 'chain',
		helpSection: 'Navigation',
		footer: 'priority',
		footerOrder: 2,
		isEnabled: inDetail,
		execute: () => {},
	},
	{
		id: 'EDIT_FIELD',
		keys: [{ specialKey: 'return' }],
		displayKey: 'Enter',
		displayText: 'edit',
		helpSection: 'Edit',
		helpLabel: 'Edit source or target path',
		footer: 'priority',
		footerOrder: 3,
		isEnabled: inDetail,
		execute: () => {},
	},
	{
		id: 'REORDER_CHAIN',
		keys: [{ textKey: 'j' }],
		displayKey: 'j / k',
		displayText: 'reorder',
		helpSection: 'Edit',
		helpLabel: 'Move transformer down (j) or up (k)',
		footer: 'priority',
		footerOrder: 4,
		isEnabled: inDetail,
		execute: () => {},
	},
	{
		id: 'ADD_TRANSFORMER',
		keys: [{ textKey: 'a' }],
		displayKey: 'a',
		displayText: 'add',
		helpSection: 'Edit',
		helpLabel: 'Add transformer to chain',
		footer: 'optional',
		isEnabled: inDetail,
		execute: () => {},
	},
	{
		id: 'REMOVE_TRANSFORMER',
		keys: [{ textKey: 'd' }],
		displayKey: 'd',
		displayText: 'remove',
		helpSection: 'Edit',
		helpLabel: 'Remove transformer from chain',
		footer: 'optional',
		isEnabled: inDetail,
		execute: () => {},
	},
	{
		id: 'CHANGE_STRATEGY',
		keys: [{ textKey: 't' }],
		displayKey: 't',
		displayText: 'strategy',
		helpSection: 'Edit',
		helpLabel: 'Change sync strategy',
		footer: 'optional',
		isEnabled: inDetail,
		execute: () => {},
	},
];

const { CommandsProvider, useCommands, COMMANDS } =
	createCommandsProvider<MeshSyncDeps>(PROJECT_COMMANDS);

export { CommandsProvider, useCommands, COMMANDS, PROJECT_COMMANDS };
export type { MeshSyncCommand, MeshSyncDeps };
