import type { SyncEntry } from '../../../types/Sync/index.js';

export const SOURCE_TYPES = [
	{ label: 'local', prefix: './', hint: 'Relative or absolute file path' },
	{ label: 'http',  prefix: 'https://', hint: 'HTTP/HTTPS URL' },
	{ label: 'git',   prefix: 'git://', hint: 'git://github.com/org/repo#branch:path' },
] as const;

export const STRATEGY_OPTIONS: { label: string; value: SyncEntry['strategy'] }[] = [
	{ label: 'manual', value: { manual: true } },
	{ label: 'watch', value: { watch: true } },
	{ label: 'poll  5s', value: { poll: '5s' } },
	{ label: 'poll 10s', value: { poll: '10s' } },
	{ label: 'poll 30s', value: { poll: '30s' } },
	{ label: 'poll  1m', value: { poll: '1m' } },
	{ label: 'poll  5m', value: { poll: '5m' } },
];

export const BUILTIN_IDS = [
	'passthrough',
	'strip-comments',
	'json-to-ts',
	'openapi-to-types',
	'strip-exports',
	'extract-types',
	'strip-tests',
	'strip-imports',
	'strip-jsdoc',
	'keep-exported',
	'yaml-to-json',
	'json-to-yaml',
	'toml-to-json',
	'env-to-ts',
	'json-to-zod',
	'csv-to-json',
	'markdown-to-html',
	'xml-to-json',
	'json-to-env',
	'graphql-to-types',
	'protobuf-to-types',
	'json-schema-to-types',
	'openapi-to-routes',
	'openapi-to-mock',
	'openapi-to-fetch',
	'asyncapi-to-types',
	'add-banner',
	'wrap-namespace',
	'wrap-module',
	'rename-exports',
	'minify',
	'prettify-json',
	'cjs-to-esm',
	'add-eslint-disable',
	'env-filter',
	'json-pick',
	'json-merge',
	'template',
	'dotenv-to-docker',
	'json-omit',
	'json-flatten',
	'truncate',
	'slice',
	'sort-lines',
	'dedupe-lines',
	'replace',
	'head',
	'tail',
	'wrap',
	'redact-secrets',
	'redact-keys',
	'strip-env-values',
	'mask-emails',
	'hash-values',
	'validate-no-secrets',
	'markdown-extract-section',
	'markdown-toc',
	'markdown-strip-badges',
	'markdown-to-plaintext',
	'markdown-rewrite-links',
	'changelog-latest',
] as const;
